<?php

use Amouhzi\PaypalCsvParser\Statement;

return [
    [
        'name' => null,
        'type' => Statement::TYPE_STANDARD_CREDIT_CARD_TRANSFER,
        'status' => Statement::STATUS_COMPLETED,
        'currency' => 'EUR',
        'gross' => 21.36,
        'fee' => 0.0,
        'net' => 21.36,
        'fromMailAddress' => null,
        'toMailAddress' => 'hassan.amouhzi@gmail.com',
        'transactionId' => 'qsdfg546qsd54g6qsd5g',
        'shippingAddress' => null,
        'itemTitle' => null,
        'itemId' => null,
        'shippingAmount' => null,
        'insuranceAmount' => null,
        'salesTax' => null,
        'option1Name' => null,
        'option1Value' => null,
        'option2Name' => null,
        'option2Value' => null,
        'referenceTxnId' => 'qsdg54d56fsg46qd5fg',
        'invoiceNumber' => null,
        'customNumber' => null,
        'receiptId' => null,
        'balance' => 21.36,
        'contactPhoneNumber' => null,
        'note' => null,
        'balanceImpact' => Statement::BALANCE_IMPACT_CREDIT,
        'datetime' => new DateTime('2015-02-21T23:43:11+01'),
        'otherPartyStatus' => null,
        'statusAddress' => null,
        'auctionSite' => null,
        'buyerId' => null,
        'itemUrl' => null,
        'closingDate' => null,
        'trustedThirdPartyNumber' => null,
        'amount' => null,
        'addressLine1' => null,
        'addressLine2' => null,
        'location' => null,
        'state' => null,
        'zipCode' => null,
        'country' => null,
        'subject' => null,
        'paymentType' => null,
        'cardType' => null,
        'transactionCode' => null,
        'paymentTrackingNumber' => null,
        'bankId' => null,
        'transactionBuyerCountryCode' => null,
        'itemDetails' => null,
        'coupons' => null,
        'purchaseVouchers' => null,
        'loyaltyCardNumber' => null,
        'authorizationCheckStatus' => null,
        'protectionEligibility' => null,
        'countryCode' => null,
        'buyerPortfolio' => null,
        'comment1' => null,
        'comment2' => null,
        'billNumber' => null,
        'orderNumber' => null,
        'customerReferenceNumber' => null,
        'payFlowTransactionNumber' => null,
        'tip' => null,
        'reduction' => null,
    ]
];
