<?php

use Amouhzi\PaypalCsvParser\Statement;

return array(
    array(
        'name' => null,
        'type' => 'Virement par carte bancaire standard',
        'status' => Statement::STATUS_COMPLETED,
        'currency' => 'EUR',
        'gross' => 12.20,
        'fee' => 0.0,
        'net' => 12.20,
        'fromMailAddress' => null,
        'toMailAddress' => 'hassan.amouhzi@gmail.com',
        'transactionId' => '1321321313D',
        'otherPartyStatus' => null,
        'shippingAddress' => null,
        'statusAddress' => null,
        'itemTitle' => null,
        'itemId' => null,
        'shippingAmount' => null,
        'insuranceAmount' => null,
        'salesTax' => null,
        'option1Name' => null,
        'option1Value' => null,
        'option2Name' => null,
        'option2Value' => null,
        'auctionSite' => null,
        'buyerId' => null,
        'itemUrl' => null,
        'closingDate' => null,
        'trustedThirdPartyNumber' => null,
        'referenceTxnId' => '2132qs1d213qsd',
        'invoiceNumber' => null,
        'customNumber' => null,
        'amount' => null,
        'receiptId' => null,
        'balance' => 12.20,
        'addressLine1' => null,
        'addressLine2' => null,
        'location' => null,
        'state' => null,
        'zipCode' => null,
        'country' => null,
        'contactPhoneNumber' => null,
        'subject' => null,
        'note' => null,
        'paymentType' => 'Carte [0000]',
        'cardType' => null,
        'transactionCode' => 'T0777',
        'paymentTrackingNumber' => null,
        'bankId' => null,
        'transactionBuyerCountryCode' => null,
        'itemDetails' => null,
        'coupons' => null,
        'purchaseVouchers' => null,
        'loyaltyCardNumber' => null,
        'authorizationCheckStatus' => null,
        'protectionEligibility' => 2,
        'countryCode' => null,
        'balanceImpact' => 'Crédit',
        'buyerPortfolio' => null,
        'comment1' => null,
        'comment2' => null,
        'billNumber' => null,
        'orderNumber' => null,
        'customerReferenceNumber' => null,
        'payflowTransactionNumber' => null,
        'tip' => null,
        'reduction' => null,
        'datetime' => new \DateTime('2014-01-31T21:33:40+01'),
        'payFlowTransactionNumber' => null,
    ),
);
